version: "3.7"

services:
  django:
    build:
      context: ./app
    env_file:
      - ./.env
    # environment:
    #   - DJANGO_READ_ENV_FILE=False
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/usr/src/app
    ports:
      - 8000:8000
